(function(){
  const money=n=>(+n||0).toLocaleString('en-US',{minimumFractionDigits:2,maximumFractionDigits:2})+' ج';
  const dateKey=d=>window.dayKeyLocal?window.dayKeyLocal(d):`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;
  const detailHref=(page,id)=>`${page}?id=${encodeURIComponent(String(id??''))}`;
  const detailLink=(page,id,label)=>id==null||String(id)===''?escR(label):`<a href="${detailHref(page,id)}">${escR(label)}</a>`;
  const escR=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
  function validDateKey(value){if(!/^\d{4}-\d{2}-\d{2}$/.test(value||''))return false;const d=new Date(value+'T12:00:00');return !Number.isNaN(d.getTime())&&dateKey(d)===value}
  function range(){
    let from=document.getElementById('repFrom')?.value,to=document.getElementById('repTo')?.value;
    let now=new Date();
    if(!from)from=`${now.getFullYear()}-${String(now.getMonth()+1).padStart(2,'0')}-01`;
    if(!to)to=dateKey(new Date(now.getFullYear(),now.getMonth()+1,0));
    if(!validDateKey(from)||!validDateKey(to))return {from,to,valid:false,reason:'اكتب تاريخًا صحيحًا في حقلي الفترة.'};
    if(from>to)return {from,to,valid:false,reason:'تاريخ البداية يجب أن يكون قبل تاريخ النهاية أو مساويًا له.'};
    return {from,to,valid:true,start:new Date(from+'T00:00:00'),end:new Date(to+'T23:59:59.999')};
  }
  function inRangeDate(v,r){if(!v)return false;const d=typeof v==='string'&&/^\d{4}-\d{2}-\d{2}$/.test(v)?new Date(v+'T12:00:00'):new Date(v);return !Number.isNaN(d.getTime())&&d>=r.start&&d<=r.end}
  function inRangeDay(v,r){if(!v)return false;const raw=String(v);const k=/^\d{4}-\d{2}-\d{2}$/.test(raw)?raw:dateKey(new Date(raw));return !!k&&k>=r.from&&k<=r.to}
  function orders(r,records=arr(K.r)){return records.filter(x=>inRangeDate(x.createdAt,r)||inRangeDate(x.closedAt,r))}
  function expenses(r){return (typeof walletTxEntries==="function"?walletTxEntries():[]).filter(x=>x.category==="مصروف تشغيل"&&inRangeDay(x.date,r))}
  function treasuryUntil(end){return arr(K.tr).filter(x=>!x.deleted&&new Date((x.date||'1970-01-01')+'T'+(x.time||'00:00'))<=end).reduce((a,x)=>a+(x.type==='in'?(+x.amount||0):-(+x.amount||0)),0)}
  function reportData(){
    const r=range(),allOrders=arr(K.r),os=orders(r,allOrders),ex=expenses(r),cs=arr(K.c),ds=arr(K.d),ps=arr(K.p),ts=arr(K.tasks).filter(x=>inRangeDay(x.date,r)),tr=arr(K.tr).filter(x=>!x.deleted&&inRangeDay(x.date,r));
    const closedOrders=os.filter(x=>x.closed&&inRangeDate(x.closedAt||x.createdAt,r)),labor=closedOrders.reduce((a,x)=>a+(+x.labor||0),0),partsSell=closedOrders.reduce((a,x)=>a+(+x.partsTotal||0),0),partsCost=closedOrders.reduce((a,x)=>a+(+x.partsCost||0),0),revenue=labor+partsSell,gross=revenue-partsCost,totalExp=ex.reduce((a,x)=>a+(x.type==="in"?-(+x.amount||0):(+x.amount||0)),0),net=gross-totalExp;
    const completed=os.filter(x=>x.closed?inRangeDate(x.closedAt||x.createdAt,r):x.status==='مكتمل').length,open=os.filter(x=>!x.closed&&x.status!=='ملغي').length,activeOrders=allOrders.filter(x=>!x.closed&&x.status!=='مكتمل'&&x.status!=='ملغي'),waiting=activeOrders.filter(x=>x.partsWaiting===true||x.partsWaiting==='yes').length,currentWorkshop=activeOrders.filter(x=>x.workshopStatus!=='تم التسليم'&&(x.executionPlace==='الورشة'||(x.workshopStatus&&x.workshopStatus!=='غير مطلوب'))).filter((x,i,a)=>a.findIndex(y=>y.id===x.id)===i),workshop=currentWorkshop.length;
    return {r,os,ex,cs,ds,ps,ts,tr,labor,partsSell,partsCost,revenue,gross,totalExp,net,completed,open,waiting,workshop,low:ps.filter(p=>(+p.qty||0)<=(+p.min||0)).length,treasuryBalance:treasuryUntil(r.end)};
  }
  function csvCell(v){const s=String(v??"");return /[",\n]/.test(s)?'"'+s.replace(/"/g,'""')+'"':s}
  function downloadCSV(filename,headers,rows){
    try{
      const lines=[headers].concat(rows).map(r=>r.map(csvCell).join(","));
      // \uFEFF (BOM) عشان إكسل يفتح الملف بالعربي صح من غير ما يتحول لرموز غريبة.
      const blob=new Blob(["\uFEFF"+lines.join("\r\n")],{type:"text/csv;charset=utf-8;"});
      const url=URL.createObjectURL(blob);
      const a=document.createElement("a");a.href=url;a.download=filename;document.body.appendChild(a);a.click();a.remove();
      setTimeout(()=>URL.revokeObjectURL(url),2000);
      return true;
    }catch(e){console.error("[reports] تعذر تصدير CSV",e);alert("تعذر إنشاء ملف CSV.");return false}
  }
  function exportOrdersCSV(){const d=reportData();downloadCSV(`تقرير-اوامر-الشغل-${d.r.from}-الى-${d.r.to}.csv`,["رقم الأمر","العميل","الجهاز","الحالة","المكان","الإجمالي","العربون"],d.os.map(o=>[o.no||"",customerName(o.customerId),deviceName(o.deviceId),o.status||"",o.executionPlace==="الورشة"?"الورشة":"العميل",(+o.total||0).toFixed(2),(+o.deposit||0).toFixed(2)]))}
  function exportInventoryCSV(){const d=reportData();downloadCSV(`تقرير-المخزن-${d.r.to}.csv`,["اسم الصنف","الكمية الحالية","الحد الأدنى","سعر الشراء","سعر البيع"],d.ps.map(p=>[p.name||"",p.qty||0,p.min||0,(+p.buy||0).toFixed(2),(+p.sell||0).toFixed(2)]))}
  function exportTreasuryCSV(){const d=reportData();downloadCSV(`تقرير-الخزنة-${d.r.from}-الى-${d.r.to}.csv`,["التاريخ","الوقت","الحركة","السبب","لمن/من","المكان","المبلغ"],d.tr.map(x=>[x.date||"",x.time||"",x.type==="in"?"وارد":"صرف",x.reason||"",x.counterparty||"",x.place||"",(+x.amount||0).toFixed(2)]))}
  function section(title,body,id){return `<section id="${id}" class="panel report-section"><div class="report-section-head"><h2>${title}</h2></div>${body}</section>`}
  function cards(d){return `<nav class="report-shortcuts" aria-label="الانتقال إلى أقسام التقرير"><a href="#report-finance">المالية</a><a href="#report-orders">أوامر الشغل</a><a href="#report-customers">العملاء</a><a href="#report-devices">الأجهزة</a><a href="#report-inventory">المخزن</a><a href="#report-workshop">الورشة</a><a href="#report-treasury">الخزنة</a><a href="#report-tasks">المهام</a></nav><div class="report-cards report-summary-cards">
    <a class="report-card report-card-link" href="#report-finance"><span>💰 الإيراد</span><b>${money(d.revenue)}</b><small>فتح التفاصيل المالية</small></a><a class="report-card report-card-link" href="#report-finance"><span>✅ صافي المكسب</span><b>${money(d.net)}</b><small>فتح التفاصيل المالية</small></a><a class="report-card report-card-link" href="#report-orders"><span>🛠️ أوامر الفترة</span><b>${d.os.length}</b><small>عرض الأوامر</small></a><a class="report-card report-card-link" href="#report-orders"><span>🔒 مكتملة/مغلقة</span><b>${d.completed}</b><small>عرض الأوامر</small></a>
    <a class="report-card report-card-link" href="#report-workshop"><span>📦 انتظار قطع</span><b>${d.waiting}</b><small>فتح تقرير الورشة</small></a><a class="report-card report-card-link" href="#report-workshop"><span>🏭 في الورشة</span><b>${d.workshop}</b><small>عرض الموجود بالورشة</small></a><a class="report-card report-card-link" href="#report-customers"><span>👤 العملاء</span><b>${d.cs.length}</b><small>فتح تقرير العملاء</small></a><a class="report-card report-card-link" href="#report-inventory"><span>📦 أصناف المخزن</span><b>${d.ps.length} · منخفض ${d.low}</b><small>فتح تقرير المخزن</small></a>
  </div>`}
  function finance(d){return section('💰 التقرير المالي',`<div class="report-table-wrap"><table class="report-table-full"><tr><th>البند</th><th>القيمة</th><th>ملاحظة</th></tr><tr><td>🔨 المصنعية</td><td>${money(d.labor)}</td><td>من الأوامر المقفولة</td></tr><tr><td>🔧 قطع الغيار المحصلة</td><td>${money(d.partsSell)}</td><td>من الأوامر المقفولة</td></tr><tr><td>📦 تكلفة القطع</td><td>${money(d.partsCost)}</td><td>تكلفة القطع المستخدمة</td></tr><tr><td>💰 الإيراد</td><td>${money(d.revenue)}</td><td>مصنعية + قطع</td></tr><tr><td>📈 مكسب قبل المصاريف</td><td>${money(d.gross)}</td><td>الإيراد − تكلفة القطع</td></tr><tr><td>🧯 مصاريف التشغيل</td><td>${money(d.totalExp)}</td><td>لا تدخل في رصيد الخزنة</td></tr><tr class="report-total"><td>✅ صافي المكسب</td><td>${money(d.net)}</td><td>للنشاط</td></tr></table></div>`, 'report-finance')}
  function ordersReport(d){let rows=d.os.slice().sort((a,b)=>String(b.createdAt||'').localeCompare(String(a.createdAt||''))).map(o=>`<tr><td>${detailLink('request.html',o.id,o.no||'—')}</td><td>${detailLink('customer.html',o.customerId,customerName(o.customerId))}</td><td>${detailLink('device.html',o.deviceId,deviceName(o.deviceId))}</td><td>${escR(o.status||'—')}</td><td>${o.executionPlace==='الورشة'?'🏭 الورشة':'🏠 العميل'}</td><td>${money(o.total)}</td><td>${money(o.deposit)}</td></tr>`).join('');return section('🛠️ تقرير أوامر الشغل',`<button type="button" class="secondary small-btn no-print" data-wf-event="click" data-wf-code="exportOrdersCSV()">⬇️ تصدير CSV</button><div class="report-table-wrap"><table class="report-table-full"><tr><th>الأمر</th><th>العميل</th><th>الجهاز</th><th>الحالة</th><th>المكان</th><th>الإجمالي</th><th>العربون</th></tr>${rows||'<tr><td colspan="7">لا توجد أوامر في الفترة.</td></tr>'}</table></div>`, 'report-orders')}
  function customersReport(d){let counts={};d.os.forEach(o=>{if(o.customerId)counts[o.customerId]=(counts[o.customerId]||0)+1});let top=Object.entries(counts).sort((a,b)=>b[1]-a[1]).slice(0,10).map(([id,n])=>`<div class="report-list-row"><span>${detailLink('customer.html',id,customerName(id))}</span><b>${n} أمر</b></div>`).join('');let newC=d.cs.filter(c=>inRangeDate(c.createdAt,d.r)).length;return section('👤 تقرير العملاء',`<div class="report-cards"><div class="report-card"><span>إجمالي العملاء</span><b>${d.cs.length}</b></div><div class="report-card"><span>عملاء جدد بالفترة</span><b>${newC}</b></div><div class="report-card"><span>عملاء تعاملوا بالفترة</span><b>${Object.keys(counts).length}</b></div></div><h3>⭐ أكثر العملاء تعاملًا في الفترة</h3><div class="report-list">${top||'<div class="report-empty">لا توجد تعاملات.</div>'}</div>`, 'report-customers')}
  function devicesReport(d){let types={},brands={},serviced={};d.ds.forEach(x=>{let type=x.type||'غير محدد',brand=x.brand||'غير محدد';types[type]=(types[type]||0)+1;brands[brand]=(brands[brand]||0)+1});d.os.forEach(o=>{if(o.deviceId)serviced[o.deviceId]=(serviced[o.deviceId]||0)+1});let typeRows=Object.entries(types).sort((a,b)=>b[1]-a[1]).map(([k,v])=>`<div class="report-list-row"><span>${escR(k)}</span><b>${v}</b></div>`).join('');let brandRows=Object.entries(brands).sort((a,b)=>b[1]-a[1]).slice(0,10).map(([k,v])=>`<div class="report-list-row"><span>${escR(k)}</span><b>${v}</b></div>`).join('');let servicedRows=Object.entries(serviced).sort((a,b)=>b[1]-a[1]).slice(0,10).map(([id,n])=>{let device=d.ds.find(x=>x.id===id);return `<div class="report-list-row"><span>${detailLink('device.html',id,device?deviceName(id):'جهاز محذوف')}</span><b>${n} أمر</b></div>`}).join('');return section('🔧 تقرير الأجهزة',`<div class="report-cards"><div class="report-card"><span>إجمالي الأجهزة</span><b>${d.ds.length}</b></div><div class="report-card"><span>أنواع الأجهزة</span><b>${Object.keys(types).length}</b></div><div class="report-card"><span>الماركات</span><b>${Object.keys(brands).length}</b></div><div class="report-card"><span>أجهزة دخلت الخدمة بالفترة</span><b>${Object.keys(serviced).length}</b></div></div><div class="report-mini-grid"><div><h3>🛠️ الأجهزة الأكثر دخولًا للصيانة</h3><div class="report-list">${servicedRows||'<div class="report-empty">لا توجد أجهزة مخدومة في الفترة.</div>'}</div></div><div><h3>حسب النوع</h3><div class="report-list">${typeRows||'<div class="report-empty">لا توجد أجهزة.</div>'}</div><h3>أكثر الماركات</h3><div class="report-list">${brandRows||'<div class="report-empty">لا توجد أجهزة.</div>'}</div></div></div>`, 'report-devices')}
  function inventoryReport(d){let stockValue=d.ps.reduce((a,p)=>a+(+p.qty||0)*(+p.buy||0),0),low=d.ps.filter(p=>(+p.qty||0)<=(+p.min||0));let usage={};arr(K.m).filter(m=>inRangeDate(m.at,d.r)).forEach(m=>{if(m.partId)usage[m.partId]=(usage[m.partId]||0)+(+m.qty||0)});let usedRows=Object.entries(usage).sort((a,b)=>b[1]-a[1]).slice(0,10).map(([id,n])=>{let p=d.ps.find(x=>x.id===id);return `<div class="report-list-row"><span>${detailLink('part.html',id,p?.name||'قطعة محذوفة')}</span><b>${n}</b></div>`}).join('');let lowRows=low.slice(0,15).map(p=>`<div class="report-list-row report-danger"><span>${detailLink('part.html',p.id,p.name||'قطعة بدون اسم')} <small>(${escR(p.qty)}/${escR(p.min)})</small></span><b>${money((+p.qty||0)*(+p.buy||0))}</b></div>`).join('');return section('📦 تقرير المخزن',`<button type="button" class="secondary small-btn no-print" data-wf-event="click" data-wf-code="exportInventoryCSV()">⬇️ تصدير CSV</button><div class="report-cards"><div class="report-card"><span>قيمة المخزون بالتكلفة</span><b>${money(stockValue)}</b></div><div class="report-card"><span>أصناف منخفضة</span><b>${low.length}</b></div><div class="report-card"><span>إجمالي الأصناف</span><b>${d.ps.length}</b></div><div class="report-card"><span>حركات بالفترة</span><b>${arr(K.m).filter(m=>inRangeDate(m.at,d.r)).length}</b></div></div><div class="report-mini-grid"><div><h3>🔥 الأكثر حركة بالفترة</h3><div class="report-list">${usedRows||'<div class="report-empty">لا توجد حركات.</div>'}</div></div><div><h3>⚠️ الأصناف المنخفضة — اضغط لفتح الصنف</h3><div class="report-list">${lowRows||'<div class="report-empty">لا توجد أصناف منخفضة.</div>'}</div></div></div>`, 'report-inventory')}
  function workshopReport(d){const current=arr(K.r).filter(o=>!o.closed&&o.status!=='مكتمل'&&o.status!=='ملغي'&&(o.workshopStatus!=='تم التسليم'&&(o.executionPlace==='الورشة'||(o.workshopStatus&&o.workshopStatus!=='غير مطلوب'))));const currentUnique=current.filter((o,i,a)=>a.findIndex(x=>x.id===o.id)===i);const delivered=arr(K.r).filter(o=>o.workshopStatus==='تم التسليم'&&inRangeDate(o.workshopAt,d.r));const rows=currentUnique.map(o=>`<tr><td>${detailLink('request.html',o.id,o.no||'—')}</td><td>${detailLink('customer.html',o.customerId,customerName(o.customerId))}</td><td>${detailLink('device.html',o.deviceId,deviceName(o.deviceId))}</td><td>${escR(o.workshopStatus||'غير مطلوب')}</td><td>${o.workshopAt?new Date(o.workshopAt).toLocaleString('ar-EG'):'—'}</td></tr>`).join('');const waiting=d.waiting;return section('🏭 تقرير الورشة',`<div class="report-cards"><div class="report-card"><span>أجهزة/أوامر داخل الورشة الآن</span><b>${currentUnique.length}</b></div><div class="report-card"><span>انتظار قطع</span><b>${waiting}</b></div><div class="report-card"><span>تم التسليم بالفترة</span><b>${delivered.length}</b></div></div><div class="report-table-wrap"><table class="report-table-full"><tr><th>الأمر</th><th>العميل</th><th>الجهاز</th><th>حالة الورشة</th><th>آخر تحديث</th></tr>${rows||'<tr><td colspan="5">لا توجد أجهزة داخل الورشة حاليًا.</td></tr>'}</table></div>`, 'report-workshop')}
  function treasuryReport(d){let ins=d.tr.filter(x=>x.type==='in').reduce((a,x)=>a+(+x.amount||0),0),outs=d.tr.filter(x=>x.type==='out').reduce((a,x)=>a+(+x.amount||0),0);let rows=d.tr.slice().sort((a,b)=>String(b.date+b.time).localeCompare(String(a.date+a.time))).map(x=>`<tr><td>${escR(x.date||'—')}</td><td>${escR(x.time||'—')}</td><td>${x.type==='in'?'➕ وارد':'➖ صرف'}</td><td>${escR(x.reason||'—')}</td><td>${escR(x.counterparty||'')}</td><td>${escR(x.place||'')}</td><td>${money(x.amount)}</td></tr>`).join('');return section('💵 تقرير الخزنة المستقلة',`<div class="hint">الخزنة منفصلة عن حسابات أوامر الشغل وقطع الغيار ومصاريف التشغيل. الأرقام التالية لحركات درج الخزنة فقط.</div><button type="button" class="secondary small-btn no-print" data-wf-event="click" data-wf-code="exportTreasuryCSV()">⬇️ تصدير CSV</button><div class="report-cards"><div class="report-card"><span>وارد الفترة</span><b>${money(ins)}</b></div><div class="report-card"><span>صرف الفترة</span><b>${money(outs)}</b></div><div class="report-card"><span>صافي حركة الفترة</span><b>${money(ins-outs)}</b></div><div class="report-card"><span>رصيد الدرج حتى نهاية الفترة</span><b>${money(d.treasuryBalance)}</b></div></div><div class="report-table-wrap"><table class="report-table-full"><tr><th>التاريخ</th><th>الوقت</th><th>الحركة</th><th>السبب</th><th>لمن/من</th><th>المكان</th><th>المبلغ</th></tr>${rows||'<tr><td colspan="7">لا توجد حركات خزنة في الفترة.</td></tr>'}</table></div>`, 'report-treasury')}
  function tasksReport(d){let today=dateKey(new Date()),open=d.ts.filter(t=>!t.completed).length,done=d.ts.filter(t=>t.completed).length,over=d.ts.filter(t=>!t.completed&&t.date&&t.date<today).length;return section('📋 تقرير المهام والمتابعة',`<div class="report-cards"><div class="report-card"><span>مهام الفترة</span><b>${d.ts.length}</b></div><div class="report-card"><span>مكتملة</span><b>${done}</b></div><div class="report-card"><span>مفتوحة</span><b>${open}</b></div><div class="report-card"><span>متأخرة</span><b>${over}</b></div></div><div class="report-list">${d.ts.slice().sort((a,b)=>String(a.date).localeCompare(String(b.date))).map(t=>`<div class="report-list-row"><span>${t.completed?'✅':'📋'} ${escR(t.title)} <small>• ${escR(t.date||'')}</small></span><b>${escR(t.priority||'عادية')}</b></div>`).join('')||'<div class="report-empty">لا توجد مهام في الفترة.</div>'}</div>`, 'report-tasks')}
  let renderQueued=false;
  function render(){
    const host=document.getElementById('reportsHost');if(!host||renderQueued)return;
    const fromEl=document.getElementById('repFrom'),toEl=document.getElementById('repTo'),status=document.getElementById('reportStatus'),r=range();
    [fromEl,toEl].forEach(el=>{if(el)el.removeAttribute('aria-invalid')});
    if(!r.valid){if(fromEl&&r.from&&!validDateKey(r.from))fromEl.setAttribute('aria-invalid','true');if(toEl&&r.to&&!validDateKey(r.to))toEl.setAttribute('aria-invalid','true');if(fromEl&&toEl&&r.from>r.to){fromEl.setAttribute('aria-invalid','true');toEl.setAttribute('aria-invalid','true')}if(status){status.textContent=r.reason;status.classList.add('report-status-error')}return}
    renderQueued=true;host.setAttribute('aria-busy','true');if(status){status.textContent='جاري تحديث التقارير…';status.classList.remove('report-status-error');status.setAttribute('role','status')}
    const controls=['repApply','repToday','repWeek','repMonth'].map(id=>document.getElementById(id)).filter(Boolean);controls.forEach(el=>{el.disabled=true;el.setAttribute('aria-disabled','true')});
    const run=()=>{try{const d=reportData();document.getElementById('reportPeriodLabel').textContent=`من ${d.r.from} إلى ${d.r.to}`;host.innerHTML=cards(d)+finance(d)+ordersReport(d)+customersReport(d)+devicesReport(d)+inventoryReport(d)+workshopReport(d)+treasuryReport(d)+tasksReport(d);if(status)status.textContent='تم تحديث التقارير.'}catch(e){console.error('[reports] تعذر تحديث التقارير',e);if(status){status.textContent='تعذر تحميل التقرير. تحقق من البيانات ثم اضغط «تحديث التقرير» لإعادة المحاولة.';status.classList.add('report-status-error');status.setAttribute('role','alert')}}finally{host.setAttribute('aria-busy','false');controls.forEach(el=>{el.disabled=false;el.removeAttribute('aria-disabled')});renderQueued=false}};
    if(typeof window.requestAnimationFrame==='function')window.requestAnimationFrame(run);else window.setTimeout(run,0);
  }
  function preset(kind){let now=new Date(),from,to;if(kind==='today'){from=to=dateKey(now)}else if(kind==='week'){let day=now.getDay()||7;let s=new Date(now);s.setDate(now.getDate()-day+1);let e=new Date(s);e.setDate(s.getDate()+6);from=dateKey(s);to=dateKey(e)}else if(kind==='month'){from=`${now.getFullYear()}-${String(now.getMonth()+1).padStart(2,'0')}-01`;to=dateKey(new Date(now.getFullYear(),now.getMonth()+1,0))}else{return}document.getElementById('repFrom').value=from;document.getElementById('repTo').value=to;render()}
  window.exportOrdersCSV=exportOrdersCSV;
  window.exportInventoryCSV=exportInventoryCSV;
  window.exportTreasuryCSV=exportTreasuryCSV;
  document.addEventListener('DOMContentLoaded',()=>{if(!document.getElementById('reportsHost'))return;preset('month');const apply=document.getElementById('repApply'),today=document.getElementById('repToday'),week=document.getElementById('repWeek'),month=document.getElementById('repMonth');if(apply)apply.addEventListener('click',render);if(today)today.addEventListener('click',()=>preset('today'));if(week)week.addEventListener('click',()=>preset('week'));if(month)month.addEventListener('click',()=>preset('month'));});
})();
